# fly.toml app configuration file generated for precider
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'precider'
primary_region = 'atl'

[build]

[deploy]
  release_command = "./bin/precider eval \"Precider.Release.migrate\""

[env]
  PHX_SERVER = 'true'
  PORT = '8080'
  MIX_ENV = 'prod'
  PHX_HOST = 'precider.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service.concurrency]
  type = 'connections'
  hard_limit = 1000
  soft_limit = 250

# [[http_service.checks]]
#   interval = '10s'
#   timeout = '5s'
#   grace_period = '5s'
#   method = 'GET'
#   path = '/health'

[machine]
  auto_destroy_state = 'destroy'